### ISSUE TITLE
.net standard support

### ISSUE THREAD

**Issue by edwardwilson** [eventflow/EventFlow.MongoDB#1]
EventFlow.MongoDB is built for full framework net451. Since mongo and EventFlow support .netstandard and therefore netcoreapp could the MongoDB package support it too?

**Comment by janfeyen** [comment]
hi @edwardwilson 
I'm more than willing to assist but I'm currently overloaded with work as it is. If you are willing to wait, I will eventually get to it.

Alternatively, you could create a pull request and I can merge it in?

**Comment by warren-pieterse** [comment]
packet 0.0.2 deployed to nuget, project updated to support nuget in vs 2017
