### ISSUE TITLE
Nuget publish fails

### ISSUE THREAD

**Issue by edwardwilson** [eventflow/EventFlow.MongoDB#13]
@rasmus nuget publish is failing, a 400 is being given in the logs. https://ci.appveyor.com/project/eventflow/eventflow-mongodb

It looks like it could be a version issue, as discussed in: http://help.appveyor.com/discussions/problems/8215-cannot-publish-to-nuget-get-400-bad-request-error

I do not have access to the build settings so could you take a look into this for me?

**Comment by rasmus** [comment]
@edwardwilson Never seen that before. AppVeyor has a issue here.

https://github.com/appveyor/ci/issues/1825

I guess that there's nothing to do but to upload the CI packages manually until they get it fixed.

**Comment by rasmus** [comment]
I double checked the API key and its correct

**Comment by edwardwilson** [comment]
@rasmus did you have any luck with the Nuget release? I can't seem to find away to force a new build to see if the problem exists still.

**Comment by rasmus** [comment]
@edwardwilson Sorry, haven't been i front of my PC for some time, will release the execution results now and see if I can fix any errors.

**Comment by rasmus** [comment]
@edwardwilson Hmmm, the build went through on the main project.
