### ISSUE TITLE
Enable support for simple querying from IMongoDbReadModelStore

### ISSUE THREAD

**Issue by edwardwilson** [eventflow/EventFlow.MongoDB#4]
I wanted to raise this to open discussions.

Within EventFlow there was a pull request [#20](https://github.com/eventflow/EventFlow/pull/20) made which added some simple find methods to the InMemoryReadModelStore. I believe these would be very useful within the IMongoDbReadModelStore, preventing the need to go outside of EventFlow and query mongodb directly.

My view is that InMemoryReadModelStore shouldn't be the only query option, some will be just too complex and require bare metal access. However similar methods to the ones in InMemoryReadModelStore could be useful.

I am happy to put a pull request in, however would be good to get agreement on the interface

**Comment by edwardwilson** [comment]
Exposing the MongoDb find code could allow access to the database within the EventFlow framework preventing users from needing to maintain their own access code and MongoDb instance. A suggested method for IMongoDbReadModelStore could be...

```C#
public interface IMongoDbReadModelStore<TReadModel> : IReadModelStore<TReadModel>
   where TReadModel : class, IReadModel, new()
{
    public static Task<IAsyncCursor<TReadModel>> FindAsync<TReadModel>(
	Expression<Func<TReadModel, bool>> filter,
	FindOptions<TReadModel, TReadModel> options = null,
	CancellationToken cancellationToken = null)
}
```

**Comment by wingnut808** [comment]
Hi Ed,

Would it be at all possible to include the ability to provide an expression to perform OrderBy actions on the dataset with properties of the read model.  Such as order by OrderDate Desc, Surname, Price Descending.

**Comment by janfeyen** [comment]
@edwardwilson  my apologies for the lack of communication from our side. will make an effort to be more helpful going forward.

happy with your proposal but why static? 

@wingnut808: sorting can be provided by the FindOptions<TReadModel, TReadModel> options

**Comment by janfeyen** [comment]
seems it like it might work 👍 

```c#
       public async Task<IAsyncCursor<TReadModel>> FindAsync(
            Expression<Func<TReadModel, bool>> filter,
            FindOptions<TReadModel, TReadModel> options = null,
            CancellationToken cancellationToken = default(CancellationToken))
        {
            var readModelDescription = _readModelDescriptionProvider.GetReadModelDescription<TReadModel>();
            var collection = _mongoDatabase.GetCollection<TReadModel>(readModelDescription.RootCollectionName.Value);

            return await collection.FindAsync(filter, options, cancellationToken);

        }
```

**Comment by edwardwilson** [comment]
@janfeyen My mistake, the method signature was grabbed from [MongoDb](http://api.mongodb.com/csharp/current/html/M_MongoDB_Driver_IMongoCollectionExtensions_FindAsync__1_1.htm). I removed `this IMongoCollection<TDocument> collection,` but didn't notice the static was still there.

Completely agree with your above implementation. I will get it put into a branch and open a pull request. I think it is great to allow access to the same underlying MongoDb instance as the rest of the read store for more complex querying from query handlers.
